### ISSUE TITLE
Feature Request: 3x6 and 6x3 Storehouse.

### ISSUE THREAD

**Issue by mbwtepaske** [Anoyomouse/Warehousing#14]
Two storehouses fit perfectly in between train cargo wagons, but do not share goods and a 6x6 warehouse is sometimes to big to fit in compact factory designs. 
I think a 6x3 rotatable storehouse with 350 slots would fill the gap perfectly.

**Comment by Anoyomouse** [comment]
Hey

Sorry for the delay in replying

The problem with this idea (as awesome as it is) is that the warehouse is pretty much a big chest to the game, and unfortunately the chest in the game is not a rotatable entity, which means i'd have to add a specific item as a 6x3 or a 3x6 warehouse (pre-rotated) perhaps with a recipy to change a 6x3 into a 3x6, however i don't like either solution, so at this stage i'm going to say no, i'm not going to implement this at this stage.
