### ISSUE TITLE
Request for Update to 0.15 

### ISSUE THREAD

**Issue by oneiwily** [Anoyomouse/Warehousing#15]
Version 0.15 is currently on advance stage.
is it possible to update the mod to 0.15

Thanks

**Comment by thejoshwolfe** [comment]
I was able to get the mod running with very basic updates, like changing version numbers in `info.json`. I haven't tested the logistic buildings.

**Comment by Anoyomouse** [comment]
Hey, sorry about the delay, i've accepted a merge request that updated the mod, i haven't had time myself to do this

So this should be closed, and i'll do a release shortly
