### ISSUE TITLE
Update for Factorio 0.16

### ISSUE THREAD

**Issue by CoreyJ87** [Anoyomouse/Warehousing#21]
This is  basically a QOL mod for my now. Requirement lolol. Just checking if this project is still worked on?

**Comment by olitologie** [comment]
Yes, please. I tried to modify the `info.json` (sometimes it works with old mods), but it doesn't work :(

**Comment by dgw** [comment]
Yes, it will. I don't know if @Anoyomouse is actively working on any mods these days, but when I get home (currently out of town) I should be able to give updating the mod a go. It'll be a good time to take care of the research rebalances that were requested, too.

@olitologie Can you be more specific about what doesn't work? I can do some research into the issues while I'm still traveling, and be more prepared to hit the ground running when I return.

**Comment by olitologie** [comment]
@dgw Ofcourse. I changed the file and folder name from `Warehousing v15_0.0.14.zip` to `Warehousing v16_0.0.14.zip` and in the `info.json` from

`"name": "Warehousing v15",
"factorio_version": "0.15",`

to

`"name": "Warehousing v16",
"factorio_version": "0.16",`

In most cases it works back in the days when I updated from .14 to .15.

The error from log:

` 0.617 Error ModManager.cpp:1023: Error while loading entity prototype "warehouse-basic" (container): Key "icon_size" not found in property tree at ROOT.container.warehouse-basic
Modifications: Warehousing Mod`

**Comment by dgw** [comment]
Oh, I remember reading something about that property being required in more places now. I'll add `icon_size` to the list of things that definitely need to be updated, thanks!

**Comment by CoreyJ87** [comment]
Awesome thanks guys.

**Comment by olitologie** [comment]
@dgw I'm not in lua coding but I could fixed the problem by adding 'icon_size = 32,' to the 'entity.lua'
(also change the file path &gt; version in path name) but got a new error:

'''
0.906 Mods to disable:Fehler beim Laden der Mods: Error while loading entity prototype "warehouse-requester" (logistic-container): A requester-type chest with zero request slots makes no sense.
Modifications: Warehousing Mod
'''

Hope it helps, I am in the Factorio API doc now. Maybe I find something helpfull :)

**Comment by dgw** [comment]
@olitologie Yep, I started prepping a changeset earlier that adds the `icon_size` to all definitions in `entity.lua` and `item.lua`. I'm guessing you haven't run across any item errors yet because of the file loading order (and because Factorio bails out after the first error, I think).

When I get back to my laptop later tonight, I'll go over the logistic warehouse types looking for issues like the one you reported, then maybe put up a test build since I can't test 0.16 right now on the machine I brought along. I want to expedite this process, though, so if you have time around when I'll be back on (approximately 5 hours from now) we might connect on IRC or something to iterate faster.

**Comment by dgw** [comment]
@olitologie @CoreyJ87 Can one of you test [dgw@0.16-update](https://github.com/dgw/Factorio-Warehousing/tree/0.16-update) when you get a chance and see if I missed anything? I think it's all set for 0.16, but I can't actually try it in a game until next week.

**Comment by olitologie** [comment]
@dgw I tested the basic and large warehouse and technologie. Works pretty well, thank you a lot. I will also test the logistic warehouses, but i have a new savegame and i need a little bit time to grow my base :)

**Comment by totalwar57** [comment]
Thanks so much! I was trying to fix this on my own until I ran into the logistic slot problem and hit a wall. Wiki was telling me to use num_logistic_slots instead of logistic_slots_count.

**Comment by dgw** [comment]
Sounds good enough for me if the test branch works for both of you.

@Anoyomouse, incoming 0.16-compatible release for upload to the mod portal…as soon as I remember what I did to package the last one, haha.

**Comment by Anoyomouse** [comment]
Jsut to close off this properly, the update has been pushed to the mod portal and is now available for all!
