### ISSUE TITLE
Add Buffer Warehouse/Storehouse type

### ISSUE THREAD

**Issue by dgw** [Anoyomouse/Warehousing#22]
Factorio 0.16 introduced a Buffer logistic chest type, which combines the functionality of a requester and a passive provider. Warehousing mod should have a corresponding warehouse and storehouse.

Will require at least edited versions of the existing graphics so the item and entity have the correct accent color. @Anoyomouse, can you contact the creators of the existing graphics to see if they will 1) contribute buffer variants themselves, 2) give permission for me (probably) to make a quick edit to their existing graphics with the new color, and/or 3) provide the PSD/XCF/etc. project files?

**Comment by Anoyomouse** [comment]
@dgw the original "images" are 3D models, and the guy who made them is away until at least feb next year, so please recolor one of the others for now, i'll ask him (and pester him) to do some updated graphics for us when he can

**Comment by dgw** [comment]
@Anoyomouse Worked on the buffer version recolors this afternoon, basing them on the passive provider variants. What do you think?
![screenshot 2017-12-24 18 27 48](https://user-images.githubusercontent.com/164140/34329915-c139d356-e8e0-11e7-95b1-2e959d6b4786.png)

I think the green is a bit too dark on the warehouse, but given that it takes like 20 minutes to get the selection mask right for recoloring and I didn't save the XCF files from GIMP (silly me, but oh well) I'd say these are good enough until February.

Also made sure the game loads with these sprites, and renders them correctly (as far as I can tell). Haven't tested behavior yet, that's for later after I get a 0.16 map going (or maybe when I can get Creative Mode for 0.16).
