### ISSUE TITLE
control click to load

### ISSUE THREAD

**Issue by andrewsunglaekim** [Anoyomouse/Warehousing#25]
I'm not sure if its a direct cause of warehouse mod, but there's a bug where this mod causes control clicking to not work to load stuff in 0.16

**Comment by dgw** [comment]
This mod doesn't touch control bindings at all. It only adds technology research and new items/entities. I use Warehousing in my own main save and I control-click things into chests and machines all the time.

**Comment by Anoyomouse** [comment]
Can you tell us which other mods you're running, as @dgw stated, we don't have any control logic in the code, so the warehouses should not be causing any other game logic bugs such as this

**Comment by andrewsunglaekim** [comment]
i ended up switching back to 0.15, it seems there are a bunch of compatability issues with various mods working together. I'll close for now and reopen if I can find a direct correlation. Thanks for the time
