### ISSUE TITLE
items disappearing from storage warehouse

### ISSUE THREAD

**Issue by nacjm** [Anoyomouse/Warehousing#26]
so i had a storage warehouse with the parts of my deconstructed base but now as i try to rebuild the items are disappearing from the warehouse. I watched the items trickle down into something that doesn't exist.

**Comment by Anoyomouse** [comment]
Warehouses don't have any "control" logic, and are just huge "chests" so to speak, there's nothing in warehousing that can make items disappear.

What other mods are you running?

**Comment by dgw** [comment]
Storage warehouses connect to the logistics network, so it's possible that logistic or construction robots are taking items from the warehouse as you work on rebuilding.

**Comment by dgw** [comment]
Will reopen issue if it turns out to be a bug in Warehousing, but it probably isn't. @nacjm feel free to continue troubleshooting here.
