### ISSUE TITLE
CFAN data still as only 0.15 compatible

### ISSUE THREAD

**Issue by Myricaulus** [Anoyomouse/Warehousing#29]
On current 0.1.0 release cfan does not know its actually 0.16 compatible.

**Comment by Myricaulus** [comment]
I checked the info.json and factorio mods, where everything seems ok. I actually dont know why its still listed as 0.15 in CFAN. I posted an issue on the CFAN GitHub regarding #29.

**Comment by dgw** [comment]
trakos/CFAN#19 resolved, closing.
