### ISSUE TITLE
Crashes Factorio 0.16.9+

### ISSUE THREAD

**Issue by dgw** [Anoyomouse/Warehousing#31]
Theory is that requester chest rework is causing the issue. (Wube added interactions between requester & buffer chests. Warehousing doesn't have buffer warehouses yet, but it shouldn't matter.)

**Comment by dgw** [comment]
Original report [at Factorio forums](https://forums.factorio.com/posting.php?mode=quote&f=93&p=329485#pr329485).

**Comment by Yousei9** [comment]
Probably related to this: https://forums.factorio.com/viewtopic.php?f=30&t=55963&hilit=logistic+chest
Should be fixed in 0.16.13

**Comment by dgw** [comment]
I hope so, will keep an eye out. Thanks @Yousei9!

**Comment by dgw** [comment]
Was not able to reproduce this in Factorio 0.16.12 on OS X (updated using the game's built-in updater from 0.16.6) with Warehousing 0.1.0 (stable) or 0.1.1 (in development). Starting new games with Warehousing loaded worked fine. I will need a save game that exhibits the problem and/or crash logs from Factorio to diagnose further if this issue still occurs.

If no further information is provided by the reporter (or another user experiencing the same issue) by the end of the week, I will close this issue as invalid.

**Comment by dgw** [comment]
No feedback or repro in a week, closing.
