### ISSUE TITLE
Storage Warehouse - causing lag in multiplayer

### ISSUE THREAD

**Issue by Komoden** [Anoyomouse/Warehousing#4]
Playing on a dedicated server hosted Factorio with following mods:
Bob's pack v0.12.17 (i think)
Warehousing v0.0.6
rso v1.5.1
SmartSplitters v0.12.17
SmartTrains v0.3.80
tanks for bob v1.3.2
gravestone v1.0.3
evoGUI v0.4.15

When one of the other players opens the Storage warehouse (with 2000 slots), it causes lag for the rest of us. Is some information actually transferred to other players, or is his computer just slow?

**Comment by Anoyomouse** [comment]
The warehouses include no additional logic code and are in fact just reskinned chests

When an inserter inserts an item in the the warehouse it apparently does a scan of all the slots to find an available slot, so the fuller the warehouses the more lag it will create, unfortunately there's nothing i can do about this, however kovarex has mentioned they may look into this

This is also discussed in part by UberWaffe on the forums, seen on this page of the warehouse topic: https://forums.factorio.com/viewtopic.php?f=93&t=17295&start=50

So, yeah, unfortunately it's just his PC not being able to keep up with the massive storage, either you're going to have to reduce the warehouses or get some more ram x.x

Sorry about this
