### ISSUE TITLE
Assemblers have a high cap on components for crafting

### ISSUE THREAD

**Issue by BennehR** [Anoyomouse/Warehousing#41]
Crafting the storehouse and warehouse in assemblers (only tested on mk3) allow a high number of components to be stored within them that are not required.

as an example, the assemlber will normally only hold enough materials to craft a few of the output, the assemblers are holding a stack of 400 iron for the warehouse and storehouse, this could be lowered

https://i.imgur.com/SU4VQLz.jpg
https://i.imgur.com/KZyALDZ.jpg

**Comment by Anoyomouse** [comment]
I have not tested this, however, the assembler machines seem to hold enough materials to craft 4 of the item without receiving any other items, which means that (with default recipies) they would need to store 400 iron (100 per warehouse).

Not sure what the question is here, the mod doesn't change the assemblers in any way, and being able to craft 4 warehouses with the materials seems like an okay thing to do, unless you're suggesting reducing the iron requirement of the warehouses?

**Comment by BennehR** [comment]
oh i see, i wasnt aware the assemblers held enough for 4, now that makes sense

as for the "question" i dont know how to add/change labels on github xP

this seems to be intended and just a misunderstanding ^^

**Comment by Anoyomouse** [comment]
Great, glad that's all it was, but also glad i could answer your question!
