### ISSUE TITLE
Future?

### ISSUE THREAD

**Issue by SgtSnipey** [Anoyomouse/Warehousing#49]
Do you plan to add any bigger warehouse? Cuz I keep running into the issue of building huge setup of warehouses to store all my crap.

**Comment by dgw** [comment]
I think our absolute hard limit on any potential size increase would be roughly _entity area_ × _steel chest capacity_ stacks per Warehousing entity.

@Anoyomouse, any thoughts? I don't think bigger is necessarily better, but there are some variants that actually store less in a given space than the equivalent are filled with vanilla 1x1 steel chests…

**Comment by SgtSnipey** [comment]
Hmmm Good to know I guess, Idk I would love to see a warehouse the size of the larger Factorissimo building. That would be amazing! I know that probably a little too extreme. But nevertheless, figured I would ask. See if you guys were even consider anything larger.

**Comment by dgw** [comment]
At present, nothing is planned to change as a result of this brief discussion, so I'll close the issue to get it out of the "Open" list. Nothing says it can't be reopened later. :smile_cat:
