### ISSUE TITLE
[Request] Could you include japanese locale file

### ISSUE THREAD

**Issue by Quifon** [Anoyomouse/Warehousing#6]
Please check the attached zip file.

[file]
ja/
ja/locale.cfg

[ja.zip](https://github.com/Anoyomouse/Warehousing/files/264917/ja.zip)

**Comment by Anoyomouse** [comment]
Hi Thanks for the translations, i have included them in the latest commit, can you download it and test that the translations come through correctly for the release?

Sorry it took me so long to put them in

**Comment by Quifon** [comment]
Thank you very much.
I'm rooting for you.
